# Generated by Django 6.0.1 on 2026-02-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitListUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('coach', 'Coach')], max_length=5)),
                ('is_invited', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('homepage', 'Homepage'), ('x', 'X (formerly Twitter)'), ('other_social_media', 'Other Social Media'), ('friend_referral', 'Friend Referral'), ('other', 'Other')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
