# Generated by Django 6.0.1 on 2026-02-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('coach', 'Coach')], max_length=10),
        ),
    ]
