# Generated by Django 6.0.1 on 2026-02-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_alter_waitlistuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'Waitlist User', 'verbose_name_plural': 'Waitlist Users'},
        ),
        migrations.AddField(
            model_name='waitlistuser',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waitlistuser',
            name='is_early_adopter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='waitlistuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
