# Generated by Django 6.0.1 on 2026-02-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0003_alter_waitlistuser_options_waitlistuser_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistuser',
            name='role',
            field=models.CharField(choices=[('user', 'Fitness Enthusiast'), ('coach', 'Fitness Coach/Trainer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='waitlistuser',
            name='source',
            field=models.CharField(blank=True, choices=[('homepage', 'Homepage'), ('x', 'X (formerly Twitter)'), ('social', 'Social Media'), ('search', 'Search Engine'), ('friend', 'Friend/Colleague'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
